apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-workflow-
spec:
  entrypoint: ansible
  arguments:
    parameters:
      - name: repository
        value: git@repo.git